export const types = {
    activateModal : 'Activate Modal',
    activateSnackBar: 'Activate SnackBar',
    login: 'Login',
    logout: 'Logout',
    tcgAuthorization: 'Tcg Authorization',
    payment: 'Payment',
    cartAddItem: 'Add Item',
    cartRemoveItem: 'Remove Item',
    cartCleanItem: 'Clean items',
    setSettings: 'Set settings',
    fetchCategoryQueryPosts : 'Get posts by category',
    fetchLikeQueryPosts: 'Get Query Posts',
    fetchLatestPosts: 'Get Latest Posts',
    fetchPostsByPagination: 'Get Posts by pagination',
    fetchPostById: 'Get Post',
    removePost: 'Remove Post',
    addViewToPost: "Add a view to a post",
    fetchCategories: "Get all the categories"
}